/**
 * 管理端菜单数据（appType: 1）
 */
export const adminMenus = [
  // ========== 首页 ==========
  {
    id: 'admin-home',
    title: '管理后台',
    name: 'admin-home',
    path: '/admin',
    level: 0,
    frontRoute: 'admin',
    parentId: null,
    sortOrder: 0,
    permission: '',
    icon: 'home',
    description: '管理后台首页',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-dashboard',
    title: '首页',
    name: 'admin-dashboard',
    path: '/admin/dashboard',
    level: 1,
    frontRoute: 'admin/dashboard',
    parentId: 'admin-home',
    sortOrder: 0,
    permission: '/admin/dashboard',
    icon: 'dashboard',
    description: '管理后台首页',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-dashboard-console',
    title: '控制台',
    name: 'admin-dashboard-console',
    path: '/admin/dashboard/console',
    level: 2,
    frontRoute: 'admin/dashboard/console',
    parentId: 'admin-dashboard',
    sortOrder: 0,
    permission: '/admin/dashboard/console',
    icon: 'monitor',
    description: '控制台',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-dashboard-overview',
    title: '数据概览',
    name: 'admin-dashboard-overview',
    path: '/admin/dashboard/overview',
    level: 2,
    frontRoute: 'admin/dashboard/overview',
    parentId: 'admin-dashboard',
    sortOrder: 1,
    permission: '/admin/dashboard/overview',
    icon: 'bar-chart',
    description: '数据概览',
    type: 1,
    appType: 1
  },

  // ========== 商品管理 ==========
  {
    id: 'admin-product',
    title: '商品管理',
    name: 'admin-product',
    path: '/admin/product',
    level: 0,
    frontRoute: 'admin/product',
    parentId: null,
    sortOrder: 1,
    permission: '',
    icon: 'shopping',
    description: '商品管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-product-list',
    title: '商品列表',
    name: 'admin-product-list',
    path: '/admin/product/list',
    level: 1,
    frontRoute: 'admin/product/list',
    parentId: 'admin-product',
    sortOrder: 0,
    permission: '/admin/product/list',
    icon: 'unordered-list',
    description: '商品列表',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-product-category',
    title: '商品分类',
    name: 'admin-product-category',
    path: '/admin/product/category',
    level: 1,
    frontRoute: 'admin/product/category',
    parentId: 'admin-product',
    sortOrder: 1,
    permission: '/admin/product/category',
    icon: 'folder-open',
    description: '商品分类',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-product-brand',
    title: '品牌管理',
    name: 'admin-product-brand',
    path: '/admin/product/brand',
    level: 1,
    frontRoute: 'admin/product/brand',
    parentId: 'admin-product',
    sortOrder: 2,
    permission: '/admin/product/brand',
    icon: 'trademark',
    description: '品牌管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-product-spec',
    title: '规格管理',
    name: 'admin-product-spec',
    path: '/admin/product/spec',
    level: 1,
    frontRoute: 'admin/product/spec',
    parentId: 'admin-product',
    sortOrder: 3,
    permission: '/admin/product/spec',
    icon: 'tool',
    description: '规格管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-product-evaluation',
    title: '商品评价',
    name: 'admin-product-evaluation',
    path: '/admin/product/evaluation',
    level: 1,
    frontRoute: 'admin/product/evaluation',
    parentId: 'admin-product',
    sortOrder: 4,
    permission: '/admin/product/evaluation',
    icon: 'star',
    description: '商品评价',
    type: 1,
    appType: 1
  },

  // ========== 订单管理 ==========
  {
    id: 'admin-order',
    title: '订单管理',
    name: 'admin-order',
    path: '/admin/order',
    level: 0,
    frontRoute: 'admin/order',
    parentId: null,
    sortOrder: 2,
    permission: '',
    icon: 'shopping-cart',
    description: '订单管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-order-list',
    title: '订单列表',
    name: 'admin-order-list',
    path: '/admin/order/list',
    level: 1,
    frontRoute: 'admin/order/list',
    parentId: 'admin-order',
    sortOrder: 0,
    permission: '/admin/order/list',
    icon: 'ordered-list',
    description: '订单列表',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-order-after-sale',
    title: '售后管理',
    name: 'admin-order-after-sale',
    path: '/admin/order/after-sale',
    level: 1,
    frontRoute: 'admin/order/after-sale',
    parentId: 'admin-order',
    sortOrder: 1,
    permission: '/admin/order/after-sale',
    icon: 'customer-service',
    description: '售后管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-order-refund',
    title: '退款管理',
    name: 'admin-order-refund',
    path: '/admin/order/refund',
    level: 1,
    frontRoute: 'admin/order/refund',
    parentId: 'admin-order',
    sortOrder: 2,
    permission: '/admin/order/refund',
    icon: 'transaction',
    description: '退款管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-order-invoice',
    title: '发票管理',
    name: 'admin-order-invoice',
    path: '/admin/order/invoice',
    level: 1,
    frontRoute: 'admin/order/invoice',
    parentId: 'admin-order',
    sortOrder: 3,
    permission: '/admin/order/invoice',
    icon: 'file-text',
    description: '发票管理',
    type: 1,
    appType: 1
  },

  // ========== 会员管理 ==========
  {
    id: 'admin-member',
    title: '会员管理',
    name: 'admin-member',
    path: '/admin/member',
    level: 0,
    frontRoute: 'admin/member',
    parentId: null,
    sortOrder: 3,
    permission: '',
    icon: 'user',
    description: '会员管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-member-list',
    title: '会员列表',
    name: 'admin-member-list',
    path: '/admin/member/list',
    level: 1,
    frontRoute: 'admin/member/list',
    parentId: 'admin-member',
    sortOrder: 0,
    permission: '/admin/member/list',
    icon: 'team',
    description: '会员列表',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-member-level',
    title: '会员等级',
    name: 'admin-member-level',
    path: '/admin/member/level',
    level: 1,
    frontRoute: 'admin/member/level',
    parentId: 'admin-member',
    sortOrder: 1,
    permission: '/admin/member/level',
    icon: 'crown',
    description: '会员等级',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-member-points',
    title: '会员积分',
    name: 'admin-member-points',
    path: '/admin/member/points',
    level: 1,
    frontRoute: 'admin/member/points',
    parentId: 'admin-member',
    sortOrder: 2,
    permission: '/admin/member/points',
    icon: 'gift',
    description: '会员积分',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-member-tags',
    title: '会员标签',
    name: 'admin-member-tags',
    path: '/admin/member/tags',
    level: 1,
    frontRoute: 'admin/member/tags',
    parentId: 'admin-member',
    sortOrder: 3,
    permission: '/admin/member/tags',
    icon: 'tags',
    description: '会员标签',
    type: 1,
    appType: 1
  },

  // ========== 营销管理 ==========
  {
    id: 'admin-marketing',
    title: '营销管理',
    name: 'admin-marketing',
    path: '/admin/marketing',
    level: 0,
    frontRoute: 'admin/marketing',
    parentId: null,
    sortOrder: 4,
    permission: '',
    icon: 'rocket',
    description: '营销管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-marketing-coupon',
    title: '优惠券管理',
    name: 'admin-marketing-coupon',
    path: '/admin/marketing/coupon',
    level: 1,
    frontRoute: 'admin/marketing/coupon',
    parentId: 'admin-marketing',
    sortOrder: 0,
    permission: '/admin/marketing/coupon',
    icon: 'coupon',
    description: '优惠券管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-marketing-promotion',
    title: '促销活动',
    name: 'admin-marketing-promotion',
    path: '/admin/marketing/promotion',
    level: 1,
    frontRoute: 'admin/marketing/promotion',
    parentId: 'admin-marketing',
    sortOrder: 1,
    permission: '/admin/marketing/promotion',
    icon: 'fire',
    description: '促销活动',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-marketing-seckill',
    title: '秒杀活动',
    name: 'admin-marketing-seckill',
    path: '/admin/marketing/seckill',
    level: 1,
    frontRoute: 'admin/marketing/seckill',
    parentId: 'admin-marketing',
    sortOrder: 2,
    permission: '/admin/marketing/seckill',
    icon: 'clock-circle',
    description: '秒杀活动',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-marketing-group',
    title: '拼团活动',
    name: 'admin-marketing-group',
    path: '/admin/marketing/group',
    level: 1,
    frontRoute: 'admin/marketing/group',
    parentId: 'admin-marketing',
    sortOrder: 3,
    permission: '/admin/marketing/group',
    icon: 'group',
    description: '拼团活动',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-marketing-full-reduction',
    title: '满减活动',
    name: 'admin-marketing-full-reduction',
    path: '/admin/marketing/full-reduction',
    level: 1,
    frontRoute: 'admin/marketing/full-reduction',
    parentId: 'admin-marketing',
    sortOrder: 4,
    permission: '/admin/marketing/full-reduction',
    icon: 'dollar',
    description: '满减活动',
    type: 1,
    appType: 1
  },

  // ========== 内容管理 ==========
  {
    id: 'admin-content',
    title: '内容管理',
    name: 'admin-content',
    path: '/admin/content',
    level: 0,
    frontRoute: 'admin/content',
    parentId: null,
    sortOrder: 5,
    permission: '',
    icon: 'read',
    description: '内容管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-content-article',
    title: '文章管理',
    name: 'admin-content-article',
    path: '/admin/content/article',
    level: 1,
    frontRoute: 'admin/content/article',
    parentId: 'admin-content',
    sortOrder: 0,
    permission: '/admin/content/article',
    icon: 'file-text',
    description: '文章管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-content-category',
    title: '文章分类',
    name: 'admin-content-category',
    path: '/admin/content/category',
    level: 1,
    frontRoute: 'admin/content/category',
    parentId: 'admin-content',
    sortOrder: 1,
    permission: '/admin/content/category',
    icon: 'folder',
    description: '文章分类',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-content-page',
    title: '页面管理',
    name: 'admin-content-page',
    path: '/admin/content/page',
    level: 1,
    frontRoute: 'admin/content/page',
    parentId: 'admin-content',
    sortOrder: 2,
    permission: '/admin/content/page',
    icon: 'layout',
    description: '页面管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-content-ad',
    title: '广告管理',
    name: 'admin-content-ad',
    path: '/admin/content/ad',
    level: 1,
    frontRoute: 'admin/content/ad',
    parentId: 'admin-content',
    sortOrder: 3,
    permission: '/admin/content/ad',
    icon: 'bulb',
    description: '广告管理',
    type: 1,
    appType: 1
  },

  // ========== 财务管理 ==========
  {
    id: 'admin-finance',
    title: '财务管理',
    name: 'admin-finance',
    path: '/admin/finance',
    level: 0,
    frontRoute: 'admin/finance',
    parentId: null,
    sortOrder: 6,
    permission: '',
    icon: 'dollar',
    description: '财务管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-finance-fund',
    title: '资金管理',
    name: 'admin-finance-fund',
    path: '/admin/finance/fund',
    level: 1,
    frontRoute: 'admin/finance/fund',
    parentId: 'admin-finance',
    sortOrder: 0,
    permission: '/admin/finance/fund',
    icon: 'wallet',
    description: '资金管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-finance-bill',
    title: '账单管理',
    name: 'admin-finance-bill',
    path: '/admin/finance/bill',
    level: 1,
    frontRoute: 'admin/finance/bill',
    parentId: 'admin-finance',
    sortOrder: 1,
    permission: '/admin/finance/bill',
    icon: 'file-excel',
    description: '账单管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-finance-withdraw',
    title: '提现管理',
    name: 'admin-finance-withdraw',
    path: '/admin/finance/withdraw',
    level: 1,
    frontRoute: 'admin/finance/withdraw',
    parentId: 'admin-finance',
    sortOrder: 2,
    permission: '/admin/finance/withdraw',
    icon: 'bank',
    description: '提现管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-finance-reconciliation',
    title: '对账管理',
    name: 'admin-finance-reconciliation',
    path: '/admin/finance/reconciliation',
    level: 1,
    frontRoute: 'admin/finance/reconciliation',
    parentId: 'admin-finance',
    sortOrder: 3,
    permission: '/admin/finance/reconciliation',
    icon: 'calculator',
    description: '对账管理',
    type: 1,
    appType: 1
  },

  // ========== 店铺管理 ==========
  {
    id: 'admin-store',
    title: '店铺管理',
    name: 'admin-store',
    path: '/admin/store',
    level: 0,
    frontRoute: 'admin/store',
    parentId: null,
    sortOrder: 7,
    permission: '',
    icon: 'shop',
    description: '店铺管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-store-list',
    title: '店铺列表',
    name: 'admin-store-list',
    path: '/admin/store/list',
    level: 1,
    frontRoute: 'admin/store/list',
    parentId: 'admin-store',
    sortOrder: 0,
    permission: '/admin/store/list',
    icon: 'unordered-list',
    description: '店铺列表',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-store-audit',
    title: '店铺审核',
    name: 'admin-store-audit',
    path: '/admin/store/audit',
    level: 1,
    frontRoute: 'admin/store/audit',
    parentId: 'admin-store',
    sortOrder: 1,
    permission: '/admin/store/audit',
    icon: 'audit',
    description: '店铺审核',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-store-level',
    title: '店铺等级',
    name: 'admin-store-level',
    path: '/admin/store/level',
    level: 1,
    frontRoute: 'admin/store/level',
    parentId: 'admin-store',
    sortOrder: 2,
    permission: '/admin/store/level',
    icon: 'star',
    description: '店铺等级',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-store-category',
    title: '店铺分类',
    name: 'admin-store-category',
    path: '/admin/store/category',
    level: 1,
    frontRoute: 'admin/store/category',
    parentId: 'admin-store',
    sortOrder: 3,
    permission: '/admin/store/category',
    icon: 'appstore',
    description: '店铺分类',
    type: 1,
    appType: 1
  },

  // ========== 系统设置 ==========
  {
    id: 'admin-system',
    title: '系统设置',
    name: 'admin-system',
    path: '/admin/system',
    level: 0,
    frontRoute: 'admin/system',
    parentId: null,
    sortOrder: 8,
    permission: '',
    icon: 'setting',
    description: '系统设置',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-system-basic',
    title: '基础设置',
    name: 'admin-system-basic',
    path: '/admin/system/basic',
    level: 1,
    frontRoute: 'admin/system/basic',
    parentId: 'admin-system',
    sortOrder: 0,
    permission: '/admin/system/basic',
    icon: 'tool',
    description: '基础设置',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-system-payment',
    title: '支付设置',
    name: 'admin-system-payment',
    path: '/admin/system/payment',
    level: 1,
    frontRoute: 'admin/system/payment',
    parentId: 'admin-system',
    sortOrder: 1,
    permission: '/admin/system/payment',
    icon: 'credit-card',
    description: '支付设置',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-system-logistics',
    title: '物流设置',
    name: 'admin-system-logistics',
    path: '/admin/system/logistics',
    level: 1,
    frontRoute: 'admin/system/logistics',
    parentId: 'admin-system',
    sortOrder: 2,
    permission: '/admin/system/logistics',
    icon: 'car',
    description: '物流设置',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-system-message',
    title: '消息设置',
    name: 'admin-system-message',
    path: '/admin/system/message',
    level: 1,
    frontRoute: 'admin/system/message',
    parentId: 'admin-system',
    sortOrder: 3,
    permission: '/admin/system/message',
    icon: 'message',
    description: '消息设置',
    type: 1,
    appType: 1
  },

  // ========== 权限管理 ==========
  {
    id: 'admin-permission',
    title: '权限管理',
    name: 'admin-permission',
    path: '/admin/permission',
    level: 0,
    frontRoute: 'admin/permission',
    parentId: null,
    sortOrder: 9,
    permission: '',
    icon: 'safety',
    description: '权限管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-permission-admin',
    title: '管理员管理',
    name: 'admin-permission-admin',
    path: '/admin/permission/admin',
    level: 1,
    frontRoute: 'admin/permission/admin',
    parentId: 'admin-permission',
    sortOrder: 0,
    permission: '/admin/permission/admin',
    icon: 'user',
    description: '管理员管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-permission-role',
    title: '角色管理',
    name: 'admin-permission-role',
    path: '/admin/permission/role',
    level: 1,
    frontRoute: 'admin/permission/role',
    parentId: 'admin-permission',
    sortOrder: 1,
    permission: '/admin/permission/role',
    icon: 'team',
    description: '角色管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-permission-menu',
    title: '菜单管理',
    name: 'admin-permission-menu',
    path: '/admin/permission/menu',
    level: 1,
    frontRoute: 'admin/permission/menu',
    parentId: 'admin-permission',
    sortOrder: 2,
    permission: '/admin/permission/menu',
    icon: 'menu',
    description: '菜单管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-permission-department',
    title: '部门管理',
    name: 'admin-permission-department',
    path: '/admin/permission/department',
    level: 1,
    frontRoute: 'admin/permission/department',
    parentId: 'admin-permission',
    sortOrder: 3,
    permission: '/admin/permission/department',
    icon: 'apartment',
    description: '部门管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-permission-log',
    title: '操作日志',
    name: 'admin-permission-log',
    path: '/admin/permission/log',
    level: 1,
    frontRoute: 'admin/permission/log',
    parentId: 'admin-permission',
    sortOrder: 4,
    permission: '/admin/permission/log',
    icon: 'file-text',
    description: '操作日志',
    type: 1,
    appType: 1
  },

  // ========== 直播管理 ==========
  {
    id: 'admin-live',
    title: '直播管理',
    name: 'admin-live',
    path: '/admin/live',
    level: 0,
    frontRoute: 'admin/live',
    parentId: null,
    sortOrder: 10,
    permission: '',
    icon: 'video-camera',
    description: '直播管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-live-manage',
    title: '直播管理',
    name: 'admin-live-manage',
    path: '/admin/live/manage',
    level: 1,
    frontRoute: 'admin/live/manage',
    parentId: 'admin-live',
    sortOrder: 0,
    permission: '/admin/live/manage',
    icon: 'play-circle',
    description: '直播管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-live-room',
    title: '直播间管理',
    name: 'admin-live-room',
    path: '/admin/live/room',
    level: 1,
    frontRoute: 'admin/live/room',
    parentId: 'admin-live',
    sortOrder: 1,
    permission: '/admin/live/room',
    icon: 'home',
    description: '直播间管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-live-goods',
    title: '直播商品',
    name: 'admin-live-goods',
    path: '/admin/live/goods',
    level: 1,
    frontRoute: 'admin/live/goods',
    parentId: 'admin-live',
    sortOrder: 2,
    permission: '/admin/live/goods',
    icon: 'shopping',
    description: '直播商品管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-live-statistics',
    title: '直播统计',
    name: 'admin-live-statistics',
    path: '/admin/live/statistics',
    level: 1,
    frontRoute: 'admin/live/statistics',
    parentId: 'admin-live',
    sortOrder: 3,
    permission: '/admin/live/statistics',
    icon: 'bar-chart',
    description: '直播数据统计',
    type: 1,
    appType: 1
  },

  // ========== IM客服管理 ==========
  {
    id: 'admin-im',
    title: '客服管理',
    name: 'admin-im',
    path: '/admin/im',
    level: 0,
    frontRoute: 'admin/im',
    parentId: null,
    sortOrder: 11,
    permission: '',
    icon: 'message',
    description: 'IM客服管理',
    type: 0,
    appType: 1
  },
  {
    id: 'admin-im-settings',
    title: '客服设置',
    name: 'admin-im-settings',
    path: '/admin/im/settings',
    level: 1,
    frontRoute: 'admin/im/settings',
    parentId: 'admin-im',
    sortOrder: 0,
    permission: '/admin/im/settings',
    icon: 'setting',
    description: '客服系统设置',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-im-chat',
    title: '聊天管理',
    name: 'admin-im-chat',
    path: '/admin/im/chat',
    level: 1,
    frontRoute: 'admin/im/chat',
    parentId: 'admin-im',
    sortOrder: 1,
    permission: '/admin/im/chat',
    icon: 'message',
    description: '聊天记录管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-im-ticket',
    title: '工单管理',
    name: 'admin-im-ticket',
    path: '/admin/im/ticket',
    level: 1,
    frontRoute: 'admin/im/ticket',
    parentId: 'admin-im',
    sortOrder: 2,
    permission: '/admin/im/ticket',
    icon: 'form',
    description: '客服工单管理',
    type: 1,
    appType: 1
  },
  {
    id: 'admin-im-kefu',
    title: '客服人员',
    name: 'admin-im-kefu',
    path: '/admin/im/kefu',
    level: 1,
    frontRoute: 'admin/im/kefu',
    parentId: 'admin-im',
    sortOrder: 3,
    permission: '/admin/im/kefu',
    icon: 'team',
    description: '客服人员管理',
    type: 1,
    appType: 1
  }
];