/**
 * 卖家端菜单数据（appType: 2）
 */
export const sellerMenus = [
  // ========== 店铺首页 ==========
  {
    id: 'seller-home',
    title: '卖家中心',
    name: 'seller-home',
    path: '/seller',
    level: 0,
    frontRoute: 'seller',
    parentId: null,
    sortOrder: 0,
    permission: '',
    icon: 'home',
    description: '卖家中心首页',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-dashboard',
    title: '店铺首页',
    name: 'seller-dashboard',
    path: '/seller/dashboard',
    level: 1,
    frontRoute: 'seller/dashboard',
    parentId: 'seller-home',
    sortOrder: 0,
    permission: '/seller/dashboard',
    icon: 'dashboard',
    description: '店铺首页',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-dashboard-overview',
    title: '数据概览',
    name: 'seller-dashboard-overview',
    path: '/seller/dashboard/overview',
    level: 2,
    frontRoute: 'seller/dashboard/overview',
    parentId: 'seller-dashboard',
    sortOrder: 0,
    permission: '/seller/dashboard/overview',
    icon: 'bar-chart',
    description: '数据概览',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-dashboard-business',
    title: '经营数据',
    name: 'seller-dashboard-business',
    path: '/seller/dashboard/business',
    level: 2,
    frontRoute: 'seller/dashboard/business',
    parentId: 'seller-dashboard',
    sortOrder: 1,
    permission: '/seller/dashboard/business',
    icon: 'line-chart',
    description: '经营数据',
    type: 1,
    appType: 2
  },

  // ========== 商品中心 ==========
  {
    id: 'seller-product',
    title: '商品中心',
    name: 'seller-product',
    path: '/seller/product',
    level: 0,
    frontRoute: 'seller/product',
    parentId: null,
    sortOrder: 1,
    permission: '',
    icon: 'shopping',
    description: '商品中心',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-product-add',
    title: '发布商品',
    name: 'seller-product-add',
    path: '/seller/product/add',
    level: 1,
    frontRoute: 'seller/product/add',
    parentId: 'seller-product',
    sortOrder: 0,
    permission: '/seller/product/add',
    icon: 'plus-circle',
    description: '发布商品',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-product-list',
    title: '商品管理',
    name: 'seller-product-list',
    path: '/seller/product/list',
    level: 1,
    frontRoute: 'seller/product/list',
    parentId: 'seller-product',
    sortOrder: 1,
    permission: '/seller/product/list',
    icon: 'unordered-list',
    description: '商品管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-product-category',
    title: '商品分类',
    name: 'seller-product-category',
    path: '/seller/product/category',
    level: 1,
    frontRoute: 'seller/product/category',
    parentId: 'seller-product',
    sortOrder: 2,
    permission: '/seller/product/category',
    icon: 'folder-open',
    description: '商品分类',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-product-stock',
    title: '库存管理',
    name: 'seller-product-stock',
    path: '/seller/product/stock',
    level: 1,
    frontRoute: 'seller/product/stock',
    parentId: 'seller-product',
    sortOrder: 3,
    permission: '/seller/product/stock',
    icon: 'inbox',
    description: '库存管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-product-evaluation',
    title: '评价管理',
    name: 'seller-product-evaluation',
    path: '/seller/product/evaluation',
    level: 1,
    frontRoute: 'seller/product/evaluation',
    parentId: 'seller-product',
    sortOrder: 4,
    permission: '/seller/product/evaluation',
    icon: 'star',
    description: '评价管理',
    type: 1,
    appType: 2
  },

  // ========== 订单中心 ==========
  {
    id: 'seller-order',
    title: '订单中心',
    name: 'seller-order',
    path: '/seller/order',
    level: 0,
    frontRoute: 'seller/order',
    parentId: null,
    sortOrder: 2,
    permission: '',
    icon: 'shopping-cart',
    description: '订单中心',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-order-list',
    title: '订单管理',
    name: 'seller-order-list',
    path: '/seller/order/list',
    level: 1,
    frontRoute: 'seller/order/list',
    parentId: 'seller-order',
    sortOrder: 0,
    permission: '/seller/order/list',
    icon: 'ordered-list',
    description: '订单管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-order-after-sale',
    title: '售后管理',
    name: 'seller-order-after-sale',
    path: '/seller/order/after-sale',
    level: 1,
    frontRoute: 'seller/order/after-sale',
    parentId: 'seller-order',
    sortOrder: 1,
    permission: '/seller/order/after-sale',
    icon: 'customer-service',
    description: '售后管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-order-shipment',
    title: '发货管理',
    name: 'seller-order-shipment',
    path: '/seller/order/shipment',
    level: 1,
    frontRoute: 'seller/order/shipment',
    parentId: 'seller-order',
    sortOrder: 2,
    permission: '/seller/order/shipment',
    icon: 'car',
    description: '发货管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-order-logistics',
    title: '物流管理',
    name: 'seller-order-logistics',
    path: '/seller/order/logistics',
    level: 1,
    frontRoute: 'seller/order/logistics',
    parentId: 'seller-order',
    sortOrder: 3,
    permission: '/seller/order/logistics',
    icon: 'truck',
    description: '物流管理',
    type: 1,
    appType: 2
  },

  // ========== 营销推广 ==========
  {
    id: 'seller-marketing',
    title: '营销推广',
    name: 'seller-marketing',
    path: '/seller/marketing',
    level: 0,
    frontRoute: 'seller/marketing',
    parentId: null,
    sortOrder: 3,
    permission: '',
    icon: 'rocket',
    description: '营销推广',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-marketing-coupon',
    title: '优惠券',
    name: 'seller-marketing-coupon',
    path: '/seller/marketing/coupon',
    level: 1,
    frontRoute: 'seller/marketing/coupon',
    parentId: 'seller-marketing',
    sortOrder: 0,
    permission: '/seller/marketing/coupon',
    icon: 'coupon',
    description: '优惠券',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-marketing-promotion',
    title: '促销活动',
    name: 'seller-marketing-promotion',
    path: '/seller/marketing/promotion',
    level: 1,
    frontRoute: 'seller/marketing/promotion',
    parentId: 'seller-marketing',
    sortOrder: 1,
    permission: '/seller/marketing/promotion',
    icon: 'fire',
    description: '促销活动',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-marketing-full-reduction',
    title: '满减活动',
    name: 'seller-marketing-full-reduction',
    path: '/seller/marketing/full-reduction',
    level: 1,
    frontRoute: 'seller/marketing/full-reduction',
    parentId: 'seller-marketing',
    sortOrder: 2,
    permission: '/seller/marketing/full-reduction',
    icon: 'dollar',
    description: '满减活动',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-marketing-decoration',
    title: '店铺装修',
    name: 'seller-marketing-decoration',
    path: '/seller/marketing/decoration',
    level: 1,
    frontRoute: 'seller/marketing/decoration',
    parentId: 'seller-marketing',
    sortOrder: 3,
    permission: '/seller/marketing/decoration',
    icon: 'layout',
    description: '店铺装修',
    type: 1,
    appType: 2
  },

  // ========== 客户管理 ==========
  {
    id: 'seller-customer',
    title: '客户管理',
    name: 'seller-customer',
    path: '/seller/customer',
    level: 0,
    frontRoute: 'seller/customer',
    parentId: null,
    sortOrder: 4,
    permission: '',
    icon: 'user',
    description: '客户管理',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-customer-list',
    title: '客户列表',
    name: 'seller-customer-list',
    path: '/seller/customer/list',
    level: 1,
    frontRoute: 'seller/customer/list',
    parentId: 'seller-customer',
    sortOrder: 0,
    permission: '/seller/customer/list',
    icon: 'team',
    description: '客户列表',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-customer-group',
    title: '客户分组',
    name: 'seller-customer-group',
    path: '/seller/customer/group',
    level: 1,
    frontRoute: 'seller/customer/group',
    parentId: 'seller-customer',
    sortOrder: 1,
    permission: '/seller/customer/group',
    icon: 'usergroup-add',
    description: '客户分组',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-customer-chat',
    title: '聊天记录',
    name: 'seller-customer-chat',
    path: '/seller/customer/chat',
    level: 1,
    frontRoute: 'seller/customer/chat',
    parentId: 'seller-customer',
    sortOrder: 2,
    permission: '/seller/customer/chat',
    icon: 'message',
    description: '聊天记录',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-customer-evaluation',
    title: '评价管理',
    name: 'seller-customer-evaluation',
    path: '/seller/customer/evaluation',
    level: 1,
    frontRoute: 'seller/customer/evaluation',
    parentId: 'seller-customer',
    sortOrder: 3,
    permission: '/seller/customer/evaluation',
    icon: 'star',
    description: '评价管理',
    type: 1,
    appType: 2
  },

  // ========== 财务管理 ==========
  {
    id: 'seller-finance',
    title: '财务管理',
    name: 'seller-finance',
    path: '/seller/finance',
    level: 0,
    frontRoute: 'seller/finance',
    parentId: null,
    sortOrder: 5,
    permission: '',
    icon: 'dollar',
    description: '财务管理',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-finance-fund',
    title: '资金管理',
    name: 'seller-finance-fund',
    path: '/seller/finance/fund',
    level: 1,
    frontRoute: 'seller/finance/fund',
    parentId: 'seller-finance',
    sortOrder: 0,
    permission: '/seller/finance/fund',
    icon: 'wallet',
    description: '资金管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-finance-bill',
    title: '账单明细',
    name: 'seller-finance-bill',
    path: '/seller/finance/bill',
    level: 1,
    frontRoute: 'seller/finance/bill',
    parentId: 'seller-finance',
    sortOrder: 1,
    permission: '/seller/finance/bill',
    icon: 'file-excel',
    description: '账单明细',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-finance-withdraw',
    title: '提现申请',
    name: 'seller-finance-withdraw',
    path: '/seller/finance/withdraw',
    level: 1,
    frontRoute: 'seller/finance/withdraw',
    parentId: 'seller-finance',
    sortOrder: 2,
    permission: '/seller/finance/withdraw',
    icon: 'bank',
    description: '提现申请',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-finance-invoice',
    title: '发票管理',
    name: 'seller-finance-invoice',
    path: '/seller/finance/invoice',
    level: 1,
    frontRoute: 'seller/finance/invoice',
    parentId: 'seller-finance',
    sortOrder: 3,
    permission: '/seller/finance/invoice',
    icon: 'file-text',
    description: '发票管理',
    type: 1,
    appType: 2
  },

  // ========== 店铺设置 ==========
  {
    id: 'seller-store',
    title: '店铺设置',
    name: 'seller-store',
    path: '/seller/store',
    level: 0,
    frontRoute: 'seller/store',
    parentId: null,
    sortOrder: 6,
    permission: '',
    icon: 'shop',
    description: '店铺设置',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-store-basic',
    title: '基本信息',
    name: 'seller-store-basic',
    path: '/seller/store/basic',
    level: 1,
    frontRoute: 'seller/store/basic',
    parentId: 'seller-store',
    sortOrder: 0,
    permission: '/seller/store/basic',
    icon: 'info-circle',
    description: '基本信息',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-store-freight',
    title: '运费模板',
    name: 'seller-store-freight',
    path: '/seller/store/freight',
    level: 1,
    frontRoute: 'seller/store/freight',
    parentId: 'seller-store',
    sortOrder: 1,
    permission: '/seller/store/freight',
    icon: 'car',
    description: '运费模板',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-store-service',
    title: '客服设置',
    name: 'seller-store-service',
    path: '/seller/store/service',
    level: 1,
    frontRoute: 'seller/store/service',
    parentId: 'seller-store',
    sortOrder: 2,
    permission: '/seller/store/service',
    icon: 'customer-service',
    description: '客服设置',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-store-security',
    title: '账号安全',
    name: 'seller-store-security',
    path: '/seller/store/security',
    level: 1,
    frontRoute: 'seller/store/security',
    parentId: 'seller-store',
    sortOrder: 3,
    permission: '/seller/store/security',
    icon: 'safety',
    description: '账号安全',
    type: 1,
    appType: 2
  },

  // ========== 店员管理 ==========
  {
    id: 'seller-staff',
    title: '店员管理',
    name: 'seller-staff',
    path: '/seller/staff',
    level: 0,
    frontRoute: 'seller/staff',
    parentId: null,
    sortOrder: 7,
    permission: '',
    icon: 'team',
    description: '店员管理',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-staff-list',
    title: '店员列表',
    name: 'seller-staff-list',
    path: '/seller/staff/list',
    level: 1,
    frontRoute: 'seller/staff/list',
    parentId: 'seller-staff',
    sortOrder: 0,
    permission: '/seller/staff/list',
    icon: 'user',
    description: '店员列表',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-staff-role',
    title: '角色管理',
    name: 'seller-staff-role',
    path: '/seller/staff/role',
    level: 1,
    frontRoute: 'seller/staff/role',
    parentId: 'seller-staff',
    sortOrder: 1,
    permission: '/seller/staff/role',
    icon: 'crown',
    description: '角色管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-staff-permission',
    title: '权限分配',
    name: 'seller-staff-permission',
    path: '/seller/staff/permission',
    level: 1,
    frontRoute: 'seller/staff/permission',
    parentId: 'seller-staff',
    sortOrder: 2,
    permission: '/seller/staff/permission',
    icon: 'safety-certificate',
    description: '权限分配',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-staff-log',
    title: '操作日志',
    name: 'seller-staff-log',
    path: '/seller/staff/log',
    level: 1,
    frontRoute: 'seller/staff/log',
    parentId: 'seller-staff',
    sortOrder: 3,
    permission: '/seller/staff/log',
    icon: 'file-text',
    description: '操作日志',
    type: 1,
    appType: 2
  },

  // ========== 直播中心 ==========
  {
    id: 'seller-live',
    title: '直播中心',
    name: 'seller-live',
    path: '/seller/live',
    level: 0,
    frontRoute: 'seller/live',
    parentId: null,
    sortOrder: 8,
    permission: '',
    icon: 'video-camera',
    description: '直播中心',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-live-room',
    title: '我的直播间',
    name: 'seller-live-room',
    path: '/seller/live/room',
    level: 1,
    frontRoute: 'seller/live/room',
    parentId: 'seller-live',
    sortOrder: 0,
    permission: '/seller/live/room',
    icon: 'home',
    description: '我的直播间',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-live-create',
    title: '创建直播',
    name: 'seller-live-create',
    path: '/seller/live/create',
    level: 1,
    frontRoute: 'seller/live/create',
    parentId: 'seller-live',
    sortOrder: 1,
    permission: '/seller/live/create',
    icon: 'plus-circle',
    description: '创建直播',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-live-goods',
    title: '直播商品',
    name: 'seller-live-goods',
    path: '/seller/live/goods',
    level: 1,
    frontRoute: 'seller/live/goods',
    parentId: 'seller-live',
    sortOrder: 2,
    permission: '/seller/live/goods',
    icon: 'shopping',
    description: '直播商品管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-live-statistics',
    title: '直播数据',
    name: 'seller-live-statistics',
    path: '/seller/live/statistics',
    level: 1,
    frontRoute: 'seller/live/statistics',
    parentId: 'seller-live',
    sortOrder: 3,
    permission: '/seller/live/statistics',
    icon: 'bar-chart',
    description: '直播数据统计',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-live-record',
    title: '直播记录',
    name: 'seller-live-record',
    path: '/seller/live/record',
    level: 1,
    frontRoute: 'seller/live/record',
    parentId: 'seller-live',
    sortOrder: 4,
    permission: '/seller/live/record',
    icon: 'history',
    description: '直播历史记录',
    type: 1,
    appType: 2
  },

  // ========== IM聊天 ==========
  {
    id: 'seller-im',
    title: '聊天管理',
    name: 'seller-im',
    path: '/seller/im',
    level: 0,
    frontRoute: 'seller/im',
    parentId: null,
    sortOrder: 9,
    permission: '',
    icon: 'message',
    description: 'IM聊天管理',
    type: 0,
    appType: 2
  },
  {
    id: 'seller-im-chat',
    title: '在线聊天',
    name: 'seller-im-chat',
    path: '/seller/im/chat',
    level: 1,
    frontRoute: 'seller/im/chat',
    parentId: 'seller-im',
    sortOrder: 0,
    permission: '/seller/im/chat',
    icon: 'message',
    description: '在线聊天',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-im-customer',
    title: '客户管理',
    name: 'seller-im-customer',
    path: '/seller/im/customer',
    level: 1,
    frontRoute: 'seller/im/customer',
    parentId: 'seller-im',
    sortOrder: 1,
    permission: '/seller/im/customer',
    icon: 'team',
    description: '聊天客户管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-im-group',
    title: '群组管理',
    name: 'seller-im-group',
    path: '/seller/im/group',
    level: 1,
    frontRoute: 'seller/im/group',
    parentId: 'seller-im',
    sortOrder: 2,
    permission: '/seller/im/group',
    icon: 'usergroup-add',
    description: '聊天群组管理',
    type: 1,
    appType: 2
  },
  {
    id: 'seller-im-settings',
    title: '聊天设置',
    name: 'seller-im-settings',
    path: '/seller/im/settings',
    level: 1,
    frontRoute: 'seller/im/settings',
    parentId: 'seller-im',
    sortOrder: 3,
    permission: '/seller/im/settings',
    icon: 'setting',
    description: '聊天系统设置',
    type: 1,
    appType: 2
  }
];